# Generated by Django 5.0.4 on 2024-05-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerkoclasshaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_rakha', models.CharField(max_length=40, unique=True)),
                ('email_rakha', models.EmailField(max_length=50, unique=True)),
                ('password_rakha', models.CharField(max_length=40)),
                ('password_thickcha', models.CharField(max_length=50)),
            ],
        ),
    ]
